### PR TITLE
Restructure draft accessibility SPEC

### PR DESCRIPTION
**Pull request by isabela-pf**
@MarsBarLee and I have been trying to sort out a way to handle the work and scope of this draft SPEC based on the knowledge and time we have to offer. This PR restructures the SPEC to include sub topics.

This version of the draft SPEC allows for the broad "accessibility" topic while also giving us room to contribute image description information specifically. We hope this is a solid compromise that leaves this project lots of room to grow if desired.

Some of the content removed in this PR will be moved to [accessibility.scientific-python.org](https://github.com/scientific-python/accessibility.scientific-python.org). If it helps, you can see progress on [our working PR for the website](https://github.com/isabela-pf/accessibility.scientific-python.org/pull/1).

References discussion on [scientific-python/accessibility.scientific-python.org #4](https://github.com/scientific-python/accessibility.scientific-python.org/issues/4).

Let me know if you have any questions or see any errors. Thanks in advance for any review! 🌻

### CODE REVIEW

**Comment by isabela-pf** [comment]
Hi there! I'm sure it's my mistake, but I'm not sure how to fix the code formatting so the test pass. Does anyone have docs I should look at (or want to fix it)?

**Comment by jarrodmillman** [comment]
I will take a look at it later today. I need to update a few things and I will add some text about how to run the auto-formatter, which isn't stated anywhere at the moment.

**Comment by isabela-pf** [comment]
Just wanted to check in if there's any changes I need to make on this. Let me know if there's anything I can do to help!

**Comment by isabela-pf** [comment]
I'm being the squeaky wheel! Please let me know if I can take any actions to help out.

**Comment by isabela-pf** [comment]
One more ping on this to see if I can help. While there's not a deadline, I'd rather have an accurate and up-to-date representation of the SPEC up so I'm happy to make whatever changes are needed.

**Comment by isabela-pf** [comment]
Giving this another nudge for feedback or anything I'm missing! Please let me know what I can do to move this forward.

**Comment by isabela-pf** [comment]
Hi again! Is there any update on something I can do to fix the formatting error? The test logs no longer exist so I may push something to get the tests running again.

**Review by jarrodmillman — APPROVED** [review]

**Comment by isabela-pf** [comment]
Thank you so much!

**Pull request merged**
