### PR TITLE
Add SPEC badge recommendation

### LINKED ISSUE #240: Add badges
Was raised on the BOF session.

It could be good to encourage badges like this one:

```
![Static Badge](https://img.shields.io/badge/SPEC-0%2C1%2C4-brightgreen)
```

Static Badge

(OC you can make this clickable so that it goes to the SPEC's website.)

### PR DESCRIPTION
**Pull request by jarrodmillman**
Close #240. See https://deploy-preview-305--scientific-python-specs.netlify.app/specs/purpose-and-process/#badges

TODO after getting feedback
- [x] Update [quickstart.py](https://github.com/scientific-python/specs/blob/main/quickstart.py)
- [x] Update Ecosystem Adoption section of existing SPECs
- [x] Add `layouts/shortcodes/spec_badge.html ` to scientific-python.org repo. It is something like:
```
{{- $number := .Get "number" }}
{{- $title := .Get "title" }}
{{- $tabs := slice }}
{{- $name := "Rendered badge" }}
{{- $content := printf "[![SPEC %s — %s](https://img.shields.io/badge/SPEC-%s-blue)](https://scientific-python.org/specs/spec-%0*s/)" $number $title $number 4 $number }}
{{- $tabs := $tabs | append (dict "name" $name "content" $content) }}
{{- $name := "Markdown" }}
{{- $content := printf "`[![SPEC %s — %s](https://img.shields.io/badge/SPEC-%s-blue)](https://scientific-python.org/specs/spec-%0*s/)`" $number $title $number 4 $number }}
{{- $tabs := $tabs | append (dict "name" $name "content" $content) }}

{{- $groupId := .Page.Scratch.Get "tabgroup" | default 0 -}}
{{- .Page.Scratch.Set "tabgroup" (add $groupId 1) -}}
{{ partial "_elements/tabs" (dict "ctx" . "tabs" $tabs) }}
```

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]

**Comment by tupui** [comment]
> This is fine as-is, but perhaps we also want to add a reminder along the lines of "Not all SPECs are applicable to all projects, so there is no need to try and 'earn' all badges."

Though at first maybe it's a good thing as people are more reluctant than anything else at the moment 😅 so if that can somehow motivate more people to look into it, why not I would say!

**Comment by jarrodmillman** [comment]
2024-04-02T06:03:57,351212935-07:00

**Comment by Carreau** [comment]
I don't think we really need table for such short snippets.

This is good to see how tabs work, but I think in the long run when snippets are only 1 or 2 lines we can "untabify".

**Comment by jarrodmillman** [comment]
With tabs
2024-04-02T10:20:37,396717318-07:00

**Comment by jarrodmillman** [comment]
Without tabs
2024-04-02T10:21:34,272886862-07:00

**Comment by jarrodmillman** [comment]
I prefer the version with tabs because it takes up less space and isn't as visually distracting for me. It would be great if the @scientific-python/spec-steering-committee could vote for the two options.

[with tabs](https://github.com/scientific-python/specs/pull/305#issuecomment-2032622080)
[without tabs](https://github.com/scientific-python/specs/pull/305#issuecomment-2032623491)

**Comment by ivanov** [comment]
I know I'm a dinosaur - but I appreciate the fact that `without tabs` works when I have javascript disabled, and has the proper context when rendered in a text-only browser (`w3m` in my case). (There are ways to make the tabbed version work without javascript too, using a combination of CSS and anchors)

**Comment by stefanv** [comment]
We could add noscript fallbacks, but then we'd want to do it everywhere JS is used (shortcut sidebar, eg). We don't have the bandwidth for that work built into our roadmap, but if the changes are not too invasive, we'd certainly consider such contributions to the theme.

**Comment by stefanv** [comment]
(As an aside, we do prioritize accessibility, albeit with JS enabled.)

**Pull request merged**
