### PR TITLE
Update spec0 with extended dates

### PR DESCRIPTION
**Pull request by munkm**
This PR updates the index.md file to include:
* dates out to 2026 for python support
* new quarterly deprecation cycle drop support printing

### CODE REVIEW

**Comment by munkm** [comment]
The linter is failing because of the indentation of packages in the quarterly release cycle. I think we want to keep those indentations. What do you think @Carreau ?

**Review by bsipocz — APPROVED** [review]
I think we should keep the indents, maybe the just need a `-` or similar to make it nested lists?

**Review by jarrodmillman — APPROVED** [review]

**Review by bsipocz — CHANGES_REQUESTED** [review]
Rendering is not correct yet, so I'm revoking the green checkmark to avoid accidental premature merge

**Comment by munkm** [comment]
Ok @bsipocz I fixed the formatting. What do you think now? 

@Carreau I made everything a sub-list. I didn't update your formatting script because I figured stuff might change as we automate, but I can add it if you'd like.

**Review by bsipocz — APPROVED** [review]
Looks all good now, thanks!

**Pull request merged**
