### PR TITLE
Add IPython endorsement to spec 0007.

### PR DESCRIPTION
**Pull request by Carreau**
IPython does not expose such API, but I believe contains a few location where we may use it (tests), and show examples of it (in docstrings).

The usage of seeds and reproducibility has often be a challenge for out users – in the terminal and via IPython.

Therefore I think that this is a good step forward for the ecosytems.

A couple of notes:

 - I personally don't like `rng`, I think it is too short and hard to grep for as it get many false positive, but I don't have a better alternative; yes you can use regex or ast-matching search engine, but still. It may be difficult to find if consumer use rng automatically as a metric  automatically

 - I'd love a section for consumers that explicitely state that even when both rng/seed are parameter, it would _still be great_ to compare with library version and call when possible with RNG. Otherwise people will start usign rng only when the older version they supoprt start supporting rng, which delay the whole transition

 - I'll remind that there is a `PendingDeprecationWarning` which is standard and supposed to be used for not yes deprecated stuff.

 - "use `numpy.random.default_rng` to validate", I think "validate" is incorrect, it should be "normalise", validate often returns a boolean, or raise a error, or normaliser may return a different object (unless the passed object is already normal.

 - I think the warning in `transition_to_rng` should include _since which version_ rng is available; if you maintain a library when it will be remove as some consequence but _since when it's available tells you wether you can _start_ doing the change without having version check (and if version check, which version to check for). That's the carrot. The stick is the version in which you will remove; and usually you want to avoid warnign someone of a punition when they haven't done anything yet.

   The common argument against this is "but the warning is show on the current version, so you know the  current version is the one where this started". That is untrue, you leapfrog version or start using a new function, or care about older version.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
I approve this for the endorsement, and suggest to keep the phrasing discussion in #350 and/or a new issue. Let me know @Carreau when this is good to get merged, or if we need to change this to a draft while waiting on convergent on the words.

**Comment by stefanv** [comment]
> * I personally don't like `rng`, I think it is too short and hard to grep for as it get many false positive, but I don't have a better alternative; yes you can use regex or ast-matching search engine, but still. It may be difficult to find if consumer use rng automatically as a metric  automatically

We personally don't like it either, but in a very long discussion no one came up with anything better. `prng` would have been better, already. But, now we have `default_rng` in NumPy, so for consistency we had to choose something. Original discussion linked from SPEC (see header), and on SPEC itself.

> * I'd love a section for consumers that explicitely state that even when both rng/seed are parameter, it would _still be great_ to compare with library version and call when possible with RNG. Otherwise people will start usign rng only when the older version they supoprt start supporting rng, which delay the whole transition

If I understand correctly, you want to advocate that we start warning when users use old argument? I think this is already there: "After rng becomes available in all releases within the support window suggested by SPEC 0, emit warnings as follows:..."

> * I'll remind that there is a `PendingDeprecationWarning` which is standard and supposed to be used for not yes deprecated stuff.

I don't know much about warning types, but if you and @mdhaber agree with which one to use, I'm happy to use it.

> * "use `numpy.random.default_rng` to validate", I think "validate" is incorrect, it should be "normalise", validate often returns a boolean, or raise a error, or normaliser may return a different object (unless the passed object is already normal.

We have a discussion on this [on your PR](https://github.com/scientific-python/specs/pull/350), and we'll make the change once there's agreement :+1: 

> * I think the warning in `transition_to_rng` should include _since which version_ rng is available; if you maintain a library when it will be remove as some consequence but _since when it's available tells you wether you can _start_ doing the change without having version check (and if version check, which version to check for). That's the carrot. The stick is the version in which you will remove; and usually you want to avoid warnign someone of a punition when they haven't done anything yet.

We could add this back in, @mdhaber? Note that these are recommendations, so of course libraries are free to do it whatever way they like. The SPEC is about the spirit of it, but good to get the details right too.

Overall, just want to say a great big thank you for reading the SPEC so carefully; it's much appreciate.

**Comment by Carreau** [comment]
> If I understand correctly, you want to advocate that we start warning when users use old argument? I think this is already there: "After rng becomes available in all releases within the support window suggested by SPEC 0, emit warnings as follows:..."

No, almost all the message in the spec are for library authors, I'm talking about recommendations for consumers. 

- Say rng is added in scipy 1.15
- That mean warnings will be added in scipy say 1.18. 

What I'm saying is that we should encourage consumers of API should try to do something like:

```
if scipy.__version__ < 1.15:
    stat.random(seed=1)
elif scipy.__version__ >= 1.15
   stat.random(rng=Generator())
```

So that at least we get a hint of how many library are _aware_ or rng.

Otherwise consumer will **start** using rng only once they start not supporting 1.14. That is to say likely after the release of 1.18. And you will get into the usual discussion "should we delay deprecation because no-one is using rng yet.

Which also goes into my last point, if the first time the warning is emitted is 1.18, and it say to use `rng` you need a way to tell user that it is available since 1.15; this makes iteasy to use above code snippet without having to dive through history.

Again the goal is to get consumers to switch as early as possible. 

(technically I would not even say "will be removed in XXX" I've seen too many time those promises slips). 

It's also a psychological effect. 
 - If you keep seeing "added in 1.15", "available since 1.15", "changed in 1.15" you are more likely to make the change with 1.15. 
 - If you see "will be removed in 1.18", "available until 1.18", "deprecated up to 1.18", you are more likely to wait until the release of 1.18 to do the change. 

Anyway, I just wanted to record my thoughts on improving the spec, that does not block the endorsement, so feel free to merge, and we can move each point into it's own issue.

**Comment by bsipocz** [comment]
I totally agree with your take on endorsing version checks and using the newer API as soon as it is available. Not sure how to do it though without explicitly raising a deprecationwarning even in the "Initial" phase detailed out in the SPEC.

**Pull request merged**
