### PR TITLE
Updated SPEC 2

### PR DESCRIPTION
**Pull request by Schefflera-Arboricola**
Pls LMK if we need to update the date and if I can add myself as an author here.

Thank you :)

### CODE REVIEW

**Comment by jarrodmillman** [comment]
Yes, please add yourself as an author. Thanks!! I will review this more carefully later today.

**Comment by Schefflera-Arboricola** [comment]
@jarrodmillman -- just a gentle reminder.

**Review by jarrodmillman — APPROVED** [review]

**Comment by bsipocz** [comment]
@jarrodmillman - this SPEC now has the `is-draft` on it already, so what about going ahead with merging this PR? I'm happy to do so if you prefer to have it done by someone not listed as an author.

**Comment by bsipocz** [comment]
I go ahead and rebase this as the have been changes on `main` that are not shown here (e.g the draft status).

**Comment by bsipocz** [comment]
We agreed on the DRAFT approach at the last meeting, so I go ahead and merge this now as it already provides a lot of improvements over the version that is shared on the website.

**Pull request merged**
