### PR TITLE
Change to the JSON version of the PyPi Simple API

### LINKED ISSUE #218: BUG: SPEC0 table should do numerical sort not alphabetical for versions
Version 2022.10 should come after 2022.3 not before, the sorting of version numbers should not be alphabetical.

Screenshot 2023-05-31 at 11 46 38

I'm cc-ing @alphapapa as this is something to double-check when the figure and table get auto-generated for the front end.

### PR DESCRIPTION
**Pull request by stefanv**
According to the PyPa API Reference, the `releases` key of the JSON API is deprecated:

https://warehouse.pypa.io/api-reference/json.html

Confusingly, the Simple API is recommended. The Simple API was originally described in PEP 503 (2015), but an updated version was proposed in PEP 691 (2022) that adds a JSON response.

However, this API does *not* include the same information as in the `releases` key of the current JSON API. But the PyPa authors are unlikely to add it back:

https://github.com/pypi/warehouse/issues/11991

So, this PR instead follows their recommended path, which is to parse versions from uploaded filenames (!).

Closes #218

### CODE REVIEW

**Review by jarrodmillman — APPROVED** [review]

**Comment by stefanv** [comment]
I can explicitly sort the versions, now that they are Version objects in a list, if that'd be helpful?

**Comment by bsipocz** [comment]
> I don't think this closes https://github.com/scientific-python/specs/issues/218, that was due to how the lines are actually inserted in the HTML, and may also come back up once the frontend is automated.

ahh, OK, I see that it fixes it if we assume the frontend will just copy-paste as is. In either case, I might prefer to keep that one open, or add a checkbox for https://github.com/scientific-python/specs/issues/173?

**Review by bsipocz — APPROVED** [review]

**Comment by stefanv** [comment]
Looking at the output of the script, I don't see any out-of-order items; sorry for being dense, but could you explain to me again what the problem is?

**Comment by stefanv** [comment]
What frontend are we talking about here?

**Comment by bsipocz** [comment]
Currently, all the versions and dates are stored hard-wired in the text of SPEC0, while we have the python script separately. Last week we said (with @munkm and with @jarrodmillman) that it would be nice if Adam could automate the figure and table, rather than it being hard-wired (https://github.com/scientific-python/specs/issues/173#issuecomment-1560285606)

**Comment by jarrodmillman** [comment]
I rebased on main and updated the chart and table using the script so we can see what changed. It looks like the drop schedule table needs to be a bulleted list and some cleanup is needed to remove extra whitespace in the chart.

It does look like the table is now sorted in numerical and not alphabetical order, so I think closing #218 makes sense, since we will be building off this script for #173.

I will push a fix to the script to clean up the whitespace and to make the table a bulleted list.

**Comment by bsipocz** [comment]
@stefanv - Could you also do a separate file for the drop schedule, from the bottom of the document?

**Comment by jarrodmillman** [comment]
@bsipocz This PR isn't ready. I needed Stefan's help with a shortcode, which is why it is half done. I will finish the PR later today and mark it as ready to review.

**Comment by stefanv** [comment]
The schedule is now also split out.

**Pull request merged**
