### PR TITLE
skimage: endorse SPECs 0, 1, and 4

### PR DESCRIPTION
**Pull request by stefanv**
I am proposing this to the skimage core developers today, who will sign off on this PR.
Please add a co-authored line for each of them before merging.

### CODE REVIEW

**Comment by jni** [comment]
You don't want to add spec-0 to the mix?

**Review by jarrodmillman — APPROVED** [review]

**Comment by stefanv** [comment]
Sure, happy to ass spec 0 to the mix!

**Comment by tupui** [comment]
Good idea to use co-author to say who signed this of per project. We should do this in the other PRs.

**Review by lagru — APPROVED** [review]

**Comment by bsipocz** [comment]
@stefanv - needs a rebase. 

Also, how many skimage people we need to wait to sign-off on it? I see `jni` and `lagru` and you are already on board. Maybe time to move out from draft and merge?

**Comment by bsipocz** [comment]
The original idea was that the SPEC committee members will take SPEC drafts back to their community, they do the discussion in their spaces and come back with endorsements. So with that we don't really need to track any decision making process on the scientific python side. 

OTOH, signed-off-by could be a thing.

**Comment by tupui** [comment]
Of course. On our side we just need to see some evidence that a discussion and endorsement happened on their side.

**Comment by bsipocz** [comment]
Oh, I see I mentioned the "signed off" first. It was mostly to see who else we're waiting for, e.g. it was super useful on the networkX PRs that there was a list of people in the PR text, so one could just double checked all of them gave a thumbs up.

**Comment by bsipocz** [comment]
> https://discuss.scientific-python.org/t/endorsing-specs-1-and-4/744

@jarrodmillman - fyi the link doesn't work

`Oops! That page doesn’t exist or is private.`

**Comment by bsipocz** [comment]
Lots of sign-off on this, and change of status, too, so I'm going ahead and merge.

Hurray for getting 3 SPECs out from draft state! 🎉 🎆

**Comment by JDWarner** [comment]
> @JDWarner and @soupault approved this here: https://discuss.scientific-python.org/t/endorsing-specs-1-and-4/744

To be public and clear for the record, yes I did endorse these!

**Pull request merged**
