### PR TITLE
NetworkX endorses spec4

### PR DESCRIPTION
**Pull request by jarrodmillman**
@dschult @MridulS @rossbar Give this a thumbs up if you approve.

### CODE REVIEW

**Comment by rossbar** [comment]
https://deploy-preview-203--scientific-python-specs.netlify.app/spec-0004/

I approve of this proposal in general. There are a few details that I think are worth clarifying in the SPEC itself (i.e. the distinction between "weekly" and "nightly"), but these are not blockers.

**Comment by stefanv** [comment]
+1

**Comment by jarrodmillman** [comment]
> https://deploy-preview-203--scientific-python-specs.netlify.app/spec-0004/
> 
> I approve of this proposal in general. There are a few details that I think are worth clarifying in the SPEC itself (i.e. the distinction between "weekly" and "nightly"), but these are not blockers.

Yes, there are probably a few things that need to be improved.

**Comment by bsipocz** [comment]
@dschult gave a 3D-double thumbs up, so I'm going ahead and merge this now.

**Pull request merged**
