### PR TITLE
Change status of SciPy to be a core project (no longer draft)

### PR DESCRIPTION
**Pull request by rgommers**
As discussed with the SciPy core team

### CODE REVIEW

**Comment by jarrodmillman** [comment]
@rgommers Could you point to a public discussion where this was approved or ask several members of the core team to publicly approve this PR (via a thumbs up or an approving review)?

For example, this is what we did for NetworkX:
https://github.com/scientific-python/specs/pull/105

Thanks!

**Comment by rgommers** [comment]
@larsoner, @tupui, @tylerjereddy, since you responded to this email thread - could you approve this PR?

**Review by tylerjereddy — APPROVED** [review]
LGTM, for those SciPy core devs that participated in the discussion, all were ultimately +1 in favor.

**Review by tupui — APPROVED** [review]
Thanks @rgommers. I confirm that all maintainers expressed a positive opinion about this.

**Pull request merged**
