### PR TITLE
NetworkX endorses spec1

### PR DESCRIPTION
**Pull request by jarrodmillman**
@dschult @MridulS @rossbar Give this a thumbs up if you approve.

### CODE REVIEW

**Comment by rossbar** [comment]
https://deploy-preview-202--scientific-python-specs.netlify.app/spec-0001/

**Comment by stefanv** [comment]
+1

**Comment by dschult** [comment]
+1  :)

**Review by tupui — APPROVED** [review]
Approving as well as the thumbs up are in.

(Also waiting to merge as it was in draft.)

**Comment by tupui** [comment]
Cf skimage's comments, consider adding co-authors to show who is sogming of for each projects

**Pull request merged**
