### PR TITLE
NetworkX endorses spec0

### PR DESCRIPTION
**Pull request by jarrodmillman**
@dschult @MridulS @rossbar Give this a thumbs up if you approve.

### CODE REVIEW

**Comment by rossbar** [comment]
Here's a link, for convenience: https://deploy-preview-204--scientific-python-specs.netlify.app/spec-0000/

I approve!

**Comment by stefanv** [comment]
+1

**Comment by dschult** [comment]
+1 :)

**Review by tupui — APPROVED** [review]
I see everyone's approval 👍 let's get this in then 👏

**Comment by tupui** [comment]
Any reason it was still on draft or we can merge?

**Comment by tupui** [comment]
Cf skimage's comments, consider adding co-authors to show who is sogming of for each projects

**Comment by bsipocz** [comment]
got all the thumbs ups, merging it 🎉

**Pull request merged**
