### PR TITLE
Proposal to add Pamphile Roy to the Steering committee

### PR DESCRIPTION
**Pull request by tupui**

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]

**Review by munkm — APPROVED** [review]
This seems like a great idea to me!

**Review by jarrodmillman — APPROVED** [review]

**Comment by stefanv** [comment]
:rocket:

**Comment by bsipocz** [comment]
3 approvals and a rocket, let's just merge this one, too :)

**Comment by tupui** [comment]
Thanks folks 😃

**Pull request merged**
